version: 0.2
env:
    parameter-store:
        S3_BUCKET: "otfe-bucket-name"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - aws s3 sync  ./dist/scale2 s3://$S3_BUCKET --delete --acl public-read
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/*'