version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: $S3_BUCKET_NAME
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - aws s3 sync  ./dist/scale2 s3://${S3_BUCKET} --delete --acl 'public-read' 
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/*'